//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROBO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ROBO.Properties.LogMessage", typeof(LogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010 - Versão SQL &apos;{0}&apos;, Servidor &apos;{1}&apos;, Base &apos;{2}&apos;, Usuário DB &apos;{3}&apos;, Senha DB &apos;{4}&apos;, Usuário SBO  &apos;{5}&apos;, Senha SBO  &apos;{6}&apos;, Linguagem DI &apos; {7}&apos; e Servidor Licença SBO  &apos;{8}&apos;..
        /// </summary>
        internal static string DEBU0010_9 {
            get {
                return ResourceManager.GetString("DEBU0010_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 025 - Erro ao {0}  a Ordem de Produção..
        /// </summary>
        internal static string ERRO_0025_G1 {
            get {
                return ResourceManager.GetString("ERRO_0025_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026 - Erro na entrada de produto acabado..
        /// </summary>
        internal static string ERRO_0026_0 {
            get {
                return ResourceManager.GetString("ERRO_0026_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 027 - Falha ao tentar registrar novos clientes, motivo &quot;{0}&quot;..
        /// </summary>
        internal static string ERRO_0027_1 {
            get {
                return ResourceManager.GetString("ERRO_0027_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 027 - Falha ao tentar registrar novos fornecedores, motivo &quot;{0}&quot;..
        /// </summary>
        internal static string ERRO_0028_1 {
            get {
                return ResourceManager.GetString("ERRO_0028_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003 - O SAP recusou a transação nº {0} na linha ID {1} com o item {3}. Mensagem {2}.
        /// </summary>
        internal static string ERRO_003_4 {
            get {
                return ResourceManager.GetString("ERRO_003_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 032 - Perdida a conexão estabelecida com SBO..
        /// </summary>
        internal static string ERRO_0032_0 {
            get {
                return ResourceManager.GetString("ERRO_0032_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 033 - Não foi possivel localizar o DocNum nº &apos;{0}&apos; (Jomar : {1}) no Pedido de Venda..
        /// </summary>
        internal static string Erro_0033_2 {
            get {
                return ResourceManager.GetString("Erro_0033_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 028 - Não foi encontrado nenhum item com o código de barra nº &quot;{0}&quot; (ID:{1})..
        /// </summary>
        internal static string ERRO_TRANS_28_2 {
            get {
                return ResourceManager.GetString("ERRO_TRANS_28_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001 - Não foi encontrado nenhum item com cadastro de código de barra padrão  nº {0}..
        /// </summary>
        internal static string ERRO0001_1 {
            get {
                return ResourceManager.GetString("ERRO0001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006 - Erro desconhecido. {0}.
        /// </summary>
        internal static string ERRO0006_1 {
            get {
                return ResourceManager.GetString("ERRO0006_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007 - Erro ao processar o método {0}. {1}.
        /// </summary>
        internal static string ERRO0007_1 {
            get {
                return ResourceManager.GetString("ERRO0007_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008 - Falha ao executar o procedimento. Verifique no log o motivo do erro. {0}.
        /// </summary>
        internal static string ERRO0008_G1 {
            get {
                return ResourceManager.GetString("ERRO0008_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009 - Erro interno no serviço..
        /// </summary>
        internal static string ERRO0009_1 {
            get {
                return ResourceManager.GetString("ERRO0009_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012 - Erro ao tentar estabelecer a conexão na companhia {0} (Servidor {1}) com o usuário {2} (Demorou {3} seg, para conexão). SAP : {4}.
        /// </summary>
        internal static string ERRO0012_5 {
            get {
                return ResourceManager.GetString("ERRO0012_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 013 - Erro ao tentar instânciar e utilizar o método SAPbobsCOM.Company. {0}.
        /// </summary>
        internal static string ERRO0013_1 {
            get {
                return ResourceManager.GetString("ERRO0013_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014 - Não foi possivel localizaro código do item pelo código de barra nº &quot;{0}&quot;..
        /// </summary>
        internal static string ERRO0014_G2 {
            get {
                return ResourceManager.GetString("ERRO0014_G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015 - Transação nº {0} :Não foi possivel localizar o documento {1} na tabela {2}. .
        /// </summary>
        internal static string ERRO0015_G3 {
            get {
                return ResourceManager.GetString("ERRO0015_G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 017 - Erro na excução do serviço. {0}.
        /// </summary>
        internal static string ERRO0017_1 {
            get {
                return ResourceManager.GetString("ERRO0017_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029 - Não foi localizado nenhum item ou recurso com o código de barras/recurso com código &quot;{0}&quot;..
        /// </summary>
        internal static string GLOBAL_0029_1 {
            get {
                return ResourceManager.GetString("GLOBAL_0029_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004 - Serviço inicializado..
        /// </summary>
        internal static string INFO0004_0 {
            get {
                return ResourceManager.GetString("INFO0004_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005 - Serviço finalizado..
        /// </summary>
        internal static string INFO0005_0 {
            get {
                return ResourceManager.GetString("INFO0005_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011 - Conectado com sucesso na companhia {0} (Servidor {1}) com usuário {2} (Demorou {3} seg, para conexão)..
        /// </summary>
        internal static string INFO0011_4 {
            get {
                return ResourceManager.GetString("INFO0011_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018 - A coluna [OITT_TreeType] da linha está com tipo de estrutura errada, são permitido somente os tipos &apos;A&apos;,&apos;S&apos;,&apos;P&apos; e &apos;T&apos;..
        /// </summary>
        internal static string ProductTree_e0018_0 {
            get {
                return ResourceManager.GetString("ProductTree_e0018_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 019 - Tipo de item na coluna ITT1_Type é invalido..
        /// </summary>
        internal static string ProductTree_e0019_0 {
            get {
                return ResourceManager.GetString("ProductTree_e0019_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020 - Método de baixa na coluna ITT1_IssuedMthd é invalido..
        /// </summary>
        internal static string ProductTree_e0020_0 {
            get {
                return ResourceManager.GetString("ProductTree_e0020_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021 - Falha ao tentar localizar o Código do produto ({0}) no campo OITT.ItemCode..
        /// </summary>
        internal static string ProductTree_e0021_1 {
            get {
                return ResourceManager.GetString("ProductTree_e0021_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022 - Erro ao tentar efetuar {0} da Estrutura do Produto {1}..
        /// </summary>
        internal static string ProductTree_e0022_2 {
            get {
                return ResourceManager.GetString("ProductTree_e0022_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 030 - Erro ao obter os dados da tabela Sage_Transacoes na linha {0}. Erro :{1}.
        /// </summary>
        internal static string TRANS_0030_2L {
            get {
                return ResourceManager.GetString("TRANS_0030_2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031 - Não é possivel executar a transação 98 quando a quantidade é zero..
        /// </summary>
        internal static string Trans_0031_0 {
            get {
                return ResourceManager.GetString("Trans_0031_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016 - Erro ao tentar executar o pedido de venda na transação nº {0}, id {1}..
        /// </summary>
        internal static string TRANS_e0016_G2 {
            get {
                return ResourceManager.GetString("TRANS_e0016_G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 023 - Tipo de Ordem de Produção invalido..
        /// </summary>
        internal static string TRANS_e0023_0 {
            get {
                return ResourceManager.GetString("TRANS_e0023_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024 - Status invalido na Ordem de Produção..
        /// </summary>
        internal static string TRANS_e0024_0 {
            get {
                return ResourceManager.GetString("TRANS_e0024_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002 - Não foi encontrada nenhum item aberto na transação nº {0}..
        /// </summary>
        internal static string TRANS_i0002_G1 {
            get {
                return ResourceManager.GetString("TRANS_i0002_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 034 - (Transaction08 ID : {0}) Não foi possivel localizar a Ordem de Produção nº {1} para alterar o Status..
        /// </summary>
        internal static string Trans08_0034_2 {
            get {
                return ResourceManager.GetString("Trans08_0034_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 035 - (Transaction08 ID : {0}) Erro ao mudar o Status da Ordem de Produção nº {1}. {2}.
        /// </summary>
        internal static string Trans08_0035_3 {
            get {
                return ResourceManager.GetString("Trans08_0035_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 036 - (Transaction38 ID : {0}) Não foi possivel localizar a Ordem de Produção nº {1} para alterar o Status..
        /// </summary>
        internal static string Trans38_0036_2 {
            get {
                return ResourceManager.GetString("Trans38_0036_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 037 - (Transaction38 ID : {0}) Erro ao tentar atualizar a linha (Line_Jomar) na Orgem de Operação. {1}.
        /// </summary>
        internal static string Trans38_0037_2 {
            get {
                return ResourceManager.GetString("Trans38_0037_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 038 - (TransactionWO ID : {0}) Não foi possivel localizar a Ordem de Produção nº {1} para alterar o Status..
        /// </summary>
        internal static string TransWO_0038_2 {
            get {
                return ResourceManager.GetString("TransWO_0038_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 039 - (TransactionWO ID : {0}) Erro ao mudar o Status da Ordem de Produção nº {1}. {2}.
        /// </summary>
        internal static string TransWO_0039_3 {
            get {
                return ResourceManager.GetString("TransWO_0039_3", resourceCulture);
            }
        }
    }
}
